// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_check.proto

package com.ytfs.service.packet;

public final class MessageCheck {
  private MessageCheck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SpotCheckTaskListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SpotCheckTaskList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string taskId = 1;</code>
     */
    java.lang.String getTaskId();
    /**
     * <code>string taskId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    java.util.List<com.ytfs.service.packet.MessageCheck.SpotCheckTask> 
        getTaskListList();
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    com.ytfs.service.packet.MessageCheck.SpotCheckTask getTaskList(int index);
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    int getTaskListCount();
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    java.util.List<? extends com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder> 
        getTaskListOrBuilderList();
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder getTaskListOrBuilder(
        int index);
  }
  /**
   * <pre>
   *msgid=0x903a
   * </pre>
   *
   * Protobuf type {@code SpotCheckTaskList}
   */
  public  static final class SpotCheckTaskList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SpotCheckTaskList)
      SpotCheckTaskListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SpotCheckTaskList.newBuilder() to construct.
    private SpotCheckTaskList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpotCheckTaskList() {
      taskId_ = "";
      taskList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SpotCheckTaskList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                taskList_ = new java.util.ArrayList<com.ytfs.service.packet.MessageCheck.SpotCheckTask>();
                mutable_bitField0_ |= 0x00000002;
              }
              taskList_.add(
                  input.readMessage(com.ytfs.service.packet.MessageCheck.SpotCheckTask.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          taskList_ = java.util.Collections.unmodifiableList(taskList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTaskList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTaskList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ytfs.service.packet.MessageCheck.SpotCheckTaskList.class, com.ytfs.service.packet.MessageCheck.SpotCheckTaskList.Builder.class);
    }

    private int bitField0_;
    public static final int TASKID_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskId_;
    /**
     * <code>string taskId = 1;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string taskId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKLIST_FIELD_NUMBER = 2;
    private java.util.List<com.ytfs.service.packet.MessageCheck.SpotCheckTask> taskList_;
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    public java.util.List<com.ytfs.service.packet.MessageCheck.SpotCheckTask> getTaskListList() {
      return taskList_;
    }
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    public java.util.List<? extends com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder> 
        getTaskListOrBuilderList() {
      return taskList_;
    }
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    public int getTaskListCount() {
      return taskList_.size();
    }
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    public com.ytfs.service.packet.MessageCheck.SpotCheckTask getTaskList(int index) {
      return taskList_.get(index);
    }
    /**
     * <code>repeated .SpotCheckTask taskList = 2;</code>
     */
    public com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder getTaskListOrBuilder(
        int index) {
      return taskList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      for (int i = 0; i < taskList_.size(); i++) {
        output.writeMessage(2, taskList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      for (int i = 0; i < taskList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, taskList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ytfs.service.packet.MessageCheck.SpotCheckTaskList)) {
        return super.equals(obj);
      }
      com.ytfs.service.packet.MessageCheck.SpotCheckTaskList other = (com.ytfs.service.packet.MessageCheck.SpotCheckTaskList) obj;

      boolean result = true;
      result = result && getTaskId()
          .equals(other.getTaskId());
      result = result && getTaskListList()
          .equals(other.getTaskListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      if (getTaskListCount() > 0) {
        hash = (37 * hash) + TASKLIST_FIELD_NUMBER;
        hash = (53 * hash) + getTaskListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ytfs.service.packet.MessageCheck.SpotCheckTaskList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *msgid=0x903a
     * </pre>
     *
     * Protobuf type {@code SpotCheckTaskList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SpotCheckTaskList)
        com.ytfs.service.packet.MessageCheck.SpotCheckTaskListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTaskList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTaskList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ytfs.service.packet.MessageCheck.SpotCheckTaskList.class, com.ytfs.service.packet.MessageCheck.SpotCheckTaskList.Builder.class);
      }

      // Construct using com.ytfs.service.packet.MessageCheck.SpotCheckTaskList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTaskListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        taskId_ = "";

        if (taskListBuilder_ == null) {
          taskList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          taskListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTaskList_descriptor;
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckTaskList getDefaultInstanceForType() {
        return com.ytfs.service.packet.MessageCheck.SpotCheckTaskList.getDefaultInstance();
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckTaskList build() {
        com.ytfs.service.packet.MessageCheck.SpotCheckTaskList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckTaskList buildPartial() {
        com.ytfs.service.packet.MessageCheck.SpotCheckTaskList result = new com.ytfs.service.packet.MessageCheck.SpotCheckTaskList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.taskId_ = taskId_;
        if (taskListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            taskList_ = java.util.Collections.unmodifiableList(taskList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.taskList_ = taskList_;
        } else {
          result.taskList_ = taskListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ytfs.service.packet.MessageCheck.SpotCheckTaskList) {
          return mergeFrom((com.ytfs.service.packet.MessageCheck.SpotCheckTaskList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ytfs.service.packet.MessageCheck.SpotCheckTaskList other) {
        if (other == com.ytfs.service.packet.MessageCheck.SpotCheckTaskList.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (taskListBuilder_ == null) {
          if (!other.taskList_.isEmpty()) {
            if (taskList_.isEmpty()) {
              taskList_ = other.taskList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTaskListIsMutable();
              taskList_.addAll(other.taskList_);
            }
            onChanged();
          }
        } else {
          if (!other.taskList_.isEmpty()) {
            if (taskListBuilder_.isEmpty()) {
              taskListBuilder_.dispose();
              taskListBuilder_ = null;
              taskList_ = other.taskList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              taskListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTaskListFieldBuilder() : null;
            } else {
              taskListBuilder_.addAllMessages(other.taskList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ytfs.service.packet.MessageCheck.SpotCheckTaskList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ytfs.service.packet.MessageCheck.SpotCheckTaskList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskId_ = "";
      /**
       * <code>string taskId = 1;</code>
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskId = 1;</code>
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 1;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 1;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.ytfs.service.packet.MessageCheck.SpotCheckTask> taskList_ =
        java.util.Collections.emptyList();
      private void ensureTaskListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          taskList_ = new java.util.ArrayList<com.ytfs.service.packet.MessageCheck.SpotCheckTask>(taskList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ytfs.service.packet.MessageCheck.SpotCheckTask, com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder, com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder> taskListBuilder_;

      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public java.util.List<com.ytfs.service.packet.MessageCheck.SpotCheckTask> getTaskListList() {
        if (taskListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(taskList_);
        } else {
          return taskListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public int getTaskListCount() {
        if (taskListBuilder_ == null) {
          return taskList_.size();
        } else {
          return taskListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public com.ytfs.service.packet.MessageCheck.SpotCheckTask getTaskList(int index) {
        if (taskListBuilder_ == null) {
          return taskList_.get(index);
        } else {
          return taskListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder setTaskList(
          int index, com.ytfs.service.packet.MessageCheck.SpotCheckTask value) {
        if (taskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskListIsMutable();
          taskList_.set(index, value);
          onChanged();
        } else {
          taskListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder setTaskList(
          int index, com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder builderForValue) {
        if (taskListBuilder_ == null) {
          ensureTaskListIsMutable();
          taskList_.set(index, builderForValue.build());
          onChanged();
        } else {
          taskListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder addTaskList(com.ytfs.service.packet.MessageCheck.SpotCheckTask value) {
        if (taskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskListIsMutable();
          taskList_.add(value);
          onChanged();
        } else {
          taskListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder addTaskList(
          int index, com.ytfs.service.packet.MessageCheck.SpotCheckTask value) {
        if (taskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskListIsMutable();
          taskList_.add(index, value);
          onChanged();
        } else {
          taskListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder addTaskList(
          com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder builderForValue) {
        if (taskListBuilder_ == null) {
          ensureTaskListIsMutable();
          taskList_.add(builderForValue.build());
          onChanged();
        } else {
          taskListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder addTaskList(
          int index, com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder builderForValue) {
        if (taskListBuilder_ == null) {
          ensureTaskListIsMutable();
          taskList_.add(index, builderForValue.build());
          onChanged();
        } else {
          taskListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder addAllTaskList(
          java.lang.Iterable<? extends com.ytfs.service.packet.MessageCheck.SpotCheckTask> values) {
        if (taskListBuilder_ == null) {
          ensureTaskListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, taskList_);
          onChanged();
        } else {
          taskListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder clearTaskList() {
        if (taskListBuilder_ == null) {
          taskList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          taskListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public Builder removeTaskList(int index) {
        if (taskListBuilder_ == null) {
          ensureTaskListIsMutable();
          taskList_.remove(index);
          onChanged();
        } else {
          taskListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder getTaskListBuilder(
          int index) {
        return getTaskListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder getTaskListOrBuilder(
          int index) {
        if (taskListBuilder_ == null) {
          return taskList_.get(index);  } else {
          return taskListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public java.util.List<? extends com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder> 
           getTaskListOrBuilderList() {
        if (taskListBuilder_ != null) {
          return taskListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(taskList_);
        }
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder addTaskListBuilder() {
        return getTaskListFieldBuilder().addBuilder(
            com.ytfs.service.packet.MessageCheck.SpotCheckTask.getDefaultInstance());
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder addTaskListBuilder(
          int index) {
        return getTaskListFieldBuilder().addBuilder(
            index, com.ytfs.service.packet.MessageCheck.SpotCheckTask.getDefaultInstance());
      }
      /**
       * <code>repeated .SpotCheckTask taskList = 2;</code>
       */
      public java.util.List<com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder> 
           getTaskListBuilderList() {
        return getTaskListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ytfs.service.packet.MessageCheck.SpotCheckTask, com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder, com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder> 
          getTaskListFieldBuilder() {
        if (taskListBuilder_ == null) {
          taskListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ytfs.service.packet.MessageCheck.SpotCheckTask, com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder, com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder>(
                  taskList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          taskList_ = null;
        }
        return taskListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SpotCheckTaskList)
    }

    // @@protoc_insertion_point(class_scope:SpotCheckTaskList)
    private static final com.ytfs.service.packet.MessageCheck.SpotCheckTaskList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ytfs.service.packet.MessageCheck.SpotCheckTaskList();
    }

    public static com.ytfs.service.packet.MessageCheck.SpotCheckTaskList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpotCheckTaskList>
        PARSER = new com.google.protobuf.AbstractParser<SpotCheckTaskList>() {
      public SpotCheckTaskList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpotCheckTaskList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpotCheckTaskList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpotCheckTaskList> getParserForType() {
      return PARSER;
    }

    public com.ytfs.service.packet.MessageCheck.SpotCheckTaskList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SpotCheckTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SpotCheckTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string nodeId = 2;</code>
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>string addr = 3;</code>
     */
    java.lang.String getAddr();
    /**
     * <code>string addr = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddrBytes();

    /**
     * <code>bytes VHF = 4;</code>
     */
    com.google.protobuf.ByteString getVHF();
  }
  /**
   * Protobuf type {@code SpotCheckTask}
   */
  public  static final class SpotCheckTask extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SpotCheckTask)
      SpotCheckTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SpotCheckTask.newBuilder() to construct.
    private SpotCheckTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpotCheckTask() {
      id_ = 0;
      nodeId_ = "";
      addr_ = "";
      vHF_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SpotCheckTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              addr_ = s;
              break;
            }
            case 34: {

              vHF_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ytfs.service.packet.MessageCheck.SpotCheckTask.class, com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NODEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object nodeId_;
    /**
     * <code>string nodeId = 2;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDR_FIELD_NUMBER = 3;
    private volatile java.lang.Object addr_;
    /**
     * <code>string addr = 3;</code>
     */
    public java.lang.String getAddr() {
      java.lang.Object ref = addr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addr_ = s;
        return s;
      }
    }
    /**
     * <code>string addr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddrBytes() {
      java.lang.Object ref = addr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VHF_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString vHF_;
    /**
     * <code>bytes VHF = 4;</code>
     */
    public com.google.protobuf.ByteString getVHF() {
      return vHF_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNodeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeId_);
      }
      if (!getAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, addr_);
      }
      if (!vHF_.isEmpty()) {
        output.writeBytes(4, vHF_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNodeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeId_);
      }
      if (!getAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, addr_);
      }
      if (!vHF_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, vHF_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ytfs.service.packet.MessageCheck.SpotCheckTask)) {
        return super.equals(obj);
      }
      com.ytfs.service.packet.MessageCheck.SpotCheckTask other = (com.ytfs.service.packet.MessageCheck.SpotCheckTask) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getNodeId()
          .equals(other.getNodeId());
      result = result && getAddr()
          .equals(other.getAddr());
      result = result && getVHF()
          .equals(other.getVHF());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getAddr().hashCode();
      hash = (37 * hash) + VHF_FIELD_NUMBER;
      hash = (53 * hash) + getVHF().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ytfs.service.packet.MessageCheck.SpotCheckTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SpotCheckTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SpotCheckTask)
        com.ytfs.service.packet.MessageCheck.SpotCheckTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ytfs.service.packet.MessageCheck.SpotCheckTask.class, com.ytfs.service.packet.MessageCheck.SpotCheckTask.Builder.class);
      }

      // Construct using com.ytfs.service.packet.MessageCheck.SpotCheckTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        nodeId_ = "";

        addr_ = "";

        vHF_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckTask_descriptor;
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckTask getDefaultInstanceForType() {
        return com.ytfs.service.packet.MessageCheck.SpotCheckTask.getDefaultInstance();
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckTask build() {
        com.ytfs.service.packet.MessageCheck.SpotCheckTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckTask buildPartial() {
        com.ytfs.service.packet.MessageCheck.SpotCheckTask result = new com.ytfs.service.packet.MessageCheck.SpotCheckTask(this);
        result.id_ = id_;
        result.nodeId_ = nodeId_;
        result.addr_ = addr_;
        result.vHF_ = vHF_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ytfs.service.packet.MessageCheck.SpotCheckTask) {
          return mergeFrom((com.ytfs.service.packet.MessageCheck.SpotCheckTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ytfs.service.packet.MessageCheck.SpotCheckTask other) {
        if (other == com.ytfs.service.packet.MessageCheck.SpotCheckTask.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          onChanged();
        }
        if (!other.getAddr().isEmpty()) {
          addr_ = other.addr_;
          onChanged();
        }
        if (other.getVHF() != com.google.protobuf.ByteString.EMPTY) {
          setVHF(other.getVHF());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ytfs.service.packet.MessageCheck.SpotCheckTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ytfs.service.packet.MessageCheck.SpotCheckTask) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 2;</code>
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder clearNodeId() {
        
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 2;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object addr_ = "";
      /**
       * <code>string addr = 3;</code>
       */
      public java.lang.String getAddr() {
        java.lang.Object ref = addr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string addr = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddrBytes() {
        java.lang.Object ref = addr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string addr = 3;</code>
       */
      public Builder setAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string addr = 3;</code>
       */
      public Builder clearAddr() {
        
        addr_ = getDefaultInstance().getAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string addr = 3;</code>
       */
      public Builder setAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addr_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString vHF_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes VHF = 4;</code>
       */
      public com.google.protobuf.ByteString getVHF() {
        return vHF_;
      }
      /**
       * <code>bytes VHF = 4;</code>
       */
      public Builder setVHF(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vHF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes VHF = 4;</code>
       */
      public Builder clearVHF() {
        
        vHF_ = getDefaultInstance().getVHF();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SpotCheckTask)
    }

    // @@protoc_insertion_point(class_scope:SpotCheckTask)
    private static final com.ytfs.service.packet.MessageCheck.SpotCheckTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ytfs.service.packet.MessageCheck.SpotCheckTask();
    }

    public static com.ytfs.service.packet.MessageCheck.SpotCheckTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpotCheckTask>
        PARSER = new com.google.protobuf.AbstractParser<SpotCheckTask>() {
      public SpotCheckTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpotCheckTask(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpotCheckTask> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpotCheckTask> getParserForType() {
      return PARSER;
    }

    public com.ytfs.service.packet.MessageCheck.SpotCheckTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SpotCheckStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SpotCheckStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string taskId = 1;</code>
     */
    java.lang.String getTaskId();
    /**
     * <code>string taskId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>int32 percent = 2;</code>
     */
    int getPercent();

    /**
     * <code>repeated int32 invalidNodeList = 3;</code>
     */
    java.util.List<java.lang.Integer> getInvalidNodeListList();
    /**
     * <code>repeated int32 invalidNodeList = 3;</code>
     */
    int getInvalidNodeListCount();
    /**
     * <code>repeated int32 invalidNodeList = 3;</code>
     */
    int getInvalidNodeList(int index);
  }
  /**
   * <pre>
   *msgid=0xa583
   * </pre>
   *
   * Protobuf type {@code SpotCheckStatus}
   */
  public  static final class SpotCheckStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SpotCheckStatus)
      SpotCheckStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SpotCheckStatus.newBuilder() to construct.
    private SpotCheckStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpotCheckStatus() {
      taskId_ = "";
      percent_ = 0;
      invalidNodeList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SpotCheckStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 16: {

              percent_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                invalidNodeList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              invalidNodeList_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                invalidNodeList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                invalidNodeList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          invalidNodeList_ = java.util.Collections.unmodifiableList(invalidNodeList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ytfs.service.packet.MessageCheck.SpotCheckStatus.class, com.ytfs.service.packet.MessageCheck.SpotCheckStatus.Builder.class);
    }

    private int bitField0_;
    public static final int TASKID_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskId_;
    /**
     * <code>string taskId = 1;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string taskId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERCENT_FIELD_NUMBER = 2;
    private int percent_;
    /**
     * <code>int32 percent = 2;</code>
     */
    public int getPercent() {
      return percent_;
    }

    public static final int INVALIDNODELIST_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> invalidNodeList_;
    /**
     * <code>repeated int32 invalidNodeList = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getInvalidNodeListList() {
      return invalidNodeList_;
    }
    /**
     * <code>repeated int32 invalidNodeList = 3;</code>
     */
    public int getInvalidNodeListCount() {
      return invalidNodeList_.size();
    }
    /**
     * <code>repeated int32 invalidNodeList = 3;</code>
     */
    public int getInvalidNodeList(int index) {
      return invalidNodeList_.get(index);
    }
    private int invalidNodeListMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      if (percent_ != 0) {
        output.writeInt32(2, percent_);
      }
      if (getInvalidNodeListList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(invalidNodeListMemoizedSerializedSize);
      }
      for (int i = 0; i < invalidNodeList_.size(); i++) {
        output.writeInt32NoTag(invalidNodeList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      if (percent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, percent_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < invalidNodeList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(invalidNodeList_.get(i));
        }
        size += dataSize;
        if (!getInvalidNodeListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        invalidNodeListMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ytfs.service.packet.MessageCheck.SpotCheckStatus)) {
        return super.equals(obj);
      }
      com.ytfs.service.packet.MessageCheck.SpotCheckStatus other = (com.ytfs.service.packet.MessageCheck.SpotCheckStatus) obj;

      boolean result = true;
      result = result && getTaskId()
          .equals(other.getTaskId());
      result = result && (getPercent()
          == other.getPercent());
      result = result && getInvalidNodeListList()
          .equals(other.getInvalidNodeListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + PERCENT_FIELD_NUMBER;
      hash = (53 * hash) + getPercent();
      if (getInvalidNodeListCount() > 0) {
        hash = (37 * hash) + INVALIDNODELIST_FIELD_NUMBER;
        hash = (53 * hash) + getInvalidNodeListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ytfs.service.packet.MessageCheck.SpotCheckStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *msgid=0xa583
     * </pre>
     *
     * Protobuf type {@code SpotCheckStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SpotCheckStatus)
        com.ytfs.service.packet.MessageCheck.SpotCheckStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ytfs.service.packet.MessageCheck.SpotCheckStatus.class, com.ytfs.service.packet.MessageCheck.SpotCheckStatus.Builder.class);
      }

      // Construct using com.ytfs.service.packet.MessageCheck.SpotCheckStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskId_ = "";

        percent_ = 0;

        invalidNodeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ytfs.service.packet.MessageCheck.internal_static_SpotCheckStatus_descriptor;
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckStatus getDefaultInstanceForType() {
        return com.ytfs.service.packet.MessageCheck.SpotCheckStatus.getDefaultInstance();
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckStatus build() {
        com.ytfs.service.packet.MessageCheck.SpotCheckStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ytfs.service.packet.MessageCheck.SpotCheckStatus buildPartial() {
        com.ytfs.service.packet.MessageCheck.SpotCheckStatus result = new com.ytfs.service.packet.MessageCheck.SpotCheckStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.taskId_ = taskId_;
        result.percent_ = percent_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          invalidNodeList_ = java.util.Collections.unmodifiableList(invalidNodeList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.invalidNodeList_ = invalidNodeList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ytfs.service.packet.MessageCheck.SpotCheckStatus) {
          return mergeFrom((com.ytfs.service.packet.MessageCheck.SpotCheckStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ytfs.service.packet.MessageCheck.SpotCheckStatus other) {
        if (other == com.ytfs.service.packet.MessageCheck.SpotCheckStatus.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (other.getPercent() != 0) {
          setPercent(other.getPercent());
        }
        if (!other.invalidNodeList_.isEmpty()) {
          if (invalidNodeList_.isEmpty()) {
            invalidNodeList_ = other.invalidNodeList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureInvalidNodeListIsMutable();
            invalidNodeList_.addAll(other.invalidNodeList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ytfs.service.packet.MessageCheck.SpotCheckStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ytfs.service.packet.MessageCheck.SpotCheckStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskId_ = "";
      /**
       * <code>string taskId = 1;</code>
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskId = 1;</code>
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 1;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 1;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private int percent_ ;
      /**
       * <code>int32 percent = 2;</code>
       */
      public int getPercent() {
        return percent_;
      }
      /**
       * <code>int32 percent = 2;</code>
       */
      public Builder setPercent(int value) {
        
        percent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 percent = 2;</code>
       */
      public Builder clearPercent() {
        
        percent_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> invalidNodeList_ = java.util.Collections.emptyList();
      private void ensureInvalidNodeListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          invalidNodeList_ = new java.util.ArrayList<java.lang.Integer>(invalidNodeList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 invalidNodeList = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getInvalidNodeListList() {
        return java.util.Collections.unmodifiableList(invalidNodeList_);
      }
      /**
       * <code>repeated int32 invalidNodeList = 3;</code>
       */
      public int getInvalidNodeListCount() {
        return invalidNodeList_.size();
      }
      /**
       * <code>repeated int32 invalidNodeList = 3;</code>
       */
      public int getInvalidNodeList(int index) {
        return invalidNodeList_.get(index);
      }
      /**
       * <code>repeated int32 invalidNodeList = 3;</code>
       */
      public Builder setInvalidNodeList(
          int index, int value) {
        ensureInvalidNodeListIsMutable();
        invalidNodeList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 invalidNodeList = 3;</code>
       */
      public Builder addInvalidNodeList(int value) {
        ensureInvalidNodeListIsMutable();
        invalidNodeList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 invalidNodeList = 3;</code>
       */
      public Builder addAllInvalidNodeList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureInvalidNodeListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invalidNodeList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 invalidNodeList = 3;</code>
       */
      public Builder clearInvalidNodeList() {
        invalidNodeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SpotCheckStatus)
    }

    // @@protoc_insertion_point(class_scope:SpotCheckStatus)
    private static final com.ytfs.service.packet.MessageCheck.SpotCheckStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ytfs.service.packet.MessageCheck.SpotCheckStatus();
    }

    public static com.ytfs.service.packet.MessageCheck.SpotCheckStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpotCheckStatus>
        PARSER = new com.google.protobuf.AbstractParser<SpotCheckStatus>() {
      public SpotCheckStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpotCheckStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpotCheckStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpotCheckStatus> getParserForType() {
      return PARSER;
    }

    public com.ytfs.service.packet.MessageCheck.SpotCheckStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpotCheckTaskList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpotCheckTaskList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpotCheckTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpotCheckTask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpotCheckStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpotCheckStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023message_check.proto\"E\n\021SpotCheckTaskLi" +
      "st\022\016\n\006taskId\030\001 \001(\t\022 \n\010taskList\030\002 \003(\0132\016.S" +
      "potCheckTask\"F\n\rSpotCheckTask\022\n\n\002id\030\001 \001(" +
      "\005\022\016\n\006nodeId\030\002 \001(\t\022\014\n\004addr\030\003 \001(\t\022\013\n\003VHF\030\004" +
      " \001(\014\"K\n\017SpotCheckStatus\022\016\n\006taskId\030\001 \001(\t\022" +
      "\017\n\007percent\030\002 \001(\005\022\027\n\017invalidNodeList\030\003 \003(" +
      "\005B\031\n\027com.ytfs.service.packetb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SpotCheckTaskList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SpotCheckTaskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpotCheckTaskList_descriptor,
        new java.lang.String[] { "TaskId", "TaskList", });
    internal_static_SpotCheckTask_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SpotCheckTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpotCheckTask_descriptor,
        new java.lang.String[] { "Id", "NodeId", "Addr", "VHF", });
    internal_static_SpotCheckStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SpotCheckStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpotCheckStatus_descriptor,
        new java.lang.String[] { "TaskId", "Percent", "InvalidNodeList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
