// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_rebuild.proto

package com.ytfs.service.packet;

public final class MessageRebuild {
  private MessageRebuild() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TaskDescription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>repeated bytes dataHash = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDataHashList();
    /**
     * <code>repeated bytes dataHash = 2;</code>
     */
    int getDataHashCount();
    /**
     * <code>repeated bytes dataHash = 2;</code>
     */
    com.google.protobuf.ByteString getDataHash(int index);

    /**
     * <code>repeated bytes parityHash = 3;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getParityHashList();
    /**
     * <code>repeated bytes parityHash = 3;</code>
     */
    int getParityHashCount();
    /**
     * <code>repeated bytes parityHash = 3;</code>
     */
    com.google.protobuf.ByteString getParityHash(int index);

    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    java.util.List<com.ytfs.service.packet.MessageRebuild.P2PLocation> 
        getLocationsList();
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    com.ytfs.service.packet.MessageRebuild.P2PLocation getLocations(int index);
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    int getLocationsCount();
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    java.util.List<? extends com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder> 
        getLocationsOrBuilderList();
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder getLocationsOrBuilder(
        int index);

    /**
     * <code>repeated uint32 recoverId = 5;</code>
     */
    java.util.List<java.lang.Integer> getRecoverIdList();
    /**
     * <code>repeated uint32 recoverId = 5;</code>
     */
    int getRecoverIdCount();
    /**
     * <code>repeated uint32 recoverId = 5;</code>
     */
    int getRecoverId(int index);
  }
  /**
   * <pre>
   *msgid=0x7bab
   * </pre>
   *
   * Protobuf type {@code TaskDescription}
   */
  public  static final class TaskDescription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TaskDescription)
      TaskDescriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskDescription.newBuilder() to construct.
    private TaskDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskDescription() {
      id_ = 0;
      dataHash_ = java.util.Collections.emptyList();
      parityHash_ = java.util.Collections.emptyList();
      locations_ = java.util.Collections.emptyList();
      recoverId_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                dataHash_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              dataHash_.add(input.readBytes());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                parityHash_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              parityHash_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                locations_ = new java.util.ArrayList<com.ytfs.service.packet.MessageRebuild.P2PLocation>();
                mutable_bitField0_ |= 0x00000008;
              }
              locations_.add(
                  input.readMessage(com.ytfs.service.packet.MessageRebuild.P2PLocation.parser(), extensionRegistry));
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                recoverId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              recoverId_.add(input.readUInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                recoverId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                recoverId_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          dataHash_ = java.util.Collections.unmodifiableList(dataHash_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          parityHash_ = java.util.Collections.unmodifiableList(parityHash_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          locations_ = java.util.Collections.unmodifiableList(locations_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          recoverId_ = java.util.Collections.unmodifiableList(recoverId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ytfs.service.packet.MessageRebuild.internal_static_TaskDescription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ytfs.service.packet.MessageRebuild.internal_static_TaskDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ytfs.service.packet.MessageRebuild.TaskDescription.class, com.ytfs.service.packet.MessageRebuild.TaskDescription.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int DATAHASH_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> dataHash_;
    /**
     * <code>repeated bytes dataHash = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDataHashList() {
      return dataHash_;
    }
    /**
     * <code>repeated bytes dataHash = 2;</code>
     */
    public int getDataHashCount() {
      return dataHash_.size();
    }
    /**
     * <code>repeated bytes dataHash = 2;</code>
     */
    public com.google.protobuf.ByteString getDataHash(int index) {
      return dataHash_.get(index);
    }

    public static final int PARITYHASH_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> parityHash_;
    /**
     * <code>repeated bytes parityHash = 3;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getParityHashList() {
      return parityHash_;
    }
    /**
     * <code>repeated bytes parityHash = 3;</code>
     */
    public int getParityHashCount() {
      return parityHash_.size();
    }
    /**
     * <code>repeated bytes parityHash = 3;</code>
     */
    public com.google.protobuf.ByteString getParityHash(int index) {
      return parityHash_.get(index);
    }

    public static final int LOCATIONS_FIELD_NUMBER = 4;
    private java.util.List<com.ytfs.service.packet.MessageRebuild.P2PLocation> locations_;
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    public java.util.List<com.ytfs.service.packet.MessageRebuild.P2PLocation> getLocationsList() {
      return locations_;
    }
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    public java.util.List<? extends com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder> 
        getLocationsOrBuilderList() {
      return locations_;
    }
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    public int getLocationsCount() {
      return locations_.size();
    }
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    public com.ytfs.service.packet.MessageRebuild.P2PLocation getLocations(int index) {
      return locations_.get(index);
    }
    /**
     * <code>repeated .P2PLocation locations = 4;</code>
     */
    public com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder getLocationsOrBuilder(
        int index) {
      return locations_.get(index);
    }

    public static final int RECOVERID_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> recoverId_;
    /**
     * <code>repeated uint32 recoverId = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getRecoverIdList() {
      return recoverId_;
    }
    /**
     * <code>repeated uint32 recoverId = 5;</code>
     */
    public int getRecoverIdCount() {
      return recoverId_.size();
    }
    /**
     * <code>repeated uint32 recoverId = 5;</code>
     */
    public int getRecoverId(int index) {
      return recoverId_.get(index);
    }
    private int recoverIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      for (int i = 0; i < dataHash_.size(); i++) {
        output.writeBytes(2, dataHash_.get(i));
      }
      for (int i = 0; i < parityHash_.size(); i++) {
        output.writeBytes(3, parityHash_.get(i));
      }
      for (int i = 0; i < locations_.size(); i++) {
        output.writeMessage(4, locations_.get(i));
      }
      if (getRecoverIdList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(recoverIdMemoizedSerializedSize);
      }
      for (int i = 0; i < recoverId_.size(); i++) {
        output.writeUInt32NoTag(recoverId_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dataHash_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(dataHash_.get(i));
        }
        size += dataSize;
        size += 1 * getDataHashList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parityHash_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parityHash_.get(i));
        }
        size += dataSize;
        size += 1 * getParityHashList().size();
      }
      for (int i = 0; i < locations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, locations_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < recoverId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(recoverId_.get(i));
        }
        size += dataSize;
        if (!getRecoverIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        recoverIdMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ytfs.service.packet.MessageRebuild.TaskDescription)) {
        return super.equals(obj);
      }
      com.ytfs.service.packet.MessageRebuild.TaskDescription other = (com.ytfs.service.packet.MessageRebuild.TaskDescription) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getDataHashList()
          .equals(other.getDataHashList());
      result = result && getParityHashList()
          .equals(other.getParityHashList());
      result = result && getLocationsList()
          .equals(other.getLocationsList());
      result = result && getRecoverIdList()
          .equals(other.getRecoverIdList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (getDataHashCount() > 0) {
        hash = (37 * hash) + DATAHASH_FIELD_NUMBER;
        hash = (53 * hash) + getDataHashList().hashCode();
      }
      if (getParityHashCount() > 0) {
        hash = (37 * hash) + PARITYHASH_FIELD_NUMBER;
        hash = (53 * hash) + getParityHashList().hashCode();
      }
      if (getLocationsCount() > 0) {
        hash = (37 * hash) + LOCATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getLocationsList().hashCode();
      }
      if (getRecoverIdCount() > 0) {
        hash = (37 * hash) + RECOVERID_FIELD_NUMBER;
        hash = (53 * hash) + getRecoverIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageRebuild.TaskDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ytfs.service.packet.MessageRebuild.TaskDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *msgid=0x7bab
     * </pre>
     *
     * Protobuf type {@code TaskDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TaskDescription)
        com.ytfs.service.packet.MessageRebuild.TaskDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ytfs.service.packet.MessageRebuild.internal_static_TaskDescription_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ytfs.service.packet.MessageRebuild.internal_static_TaskDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ytfs.service.packet.MessageRebuild.TaskDescription.class, com.ytfs.service.packet.MessageRebuild.TaskDescription.Builder.class);
      }

      // Construct using com.ytfs.service.packet.MessageRebuild.TaskDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLocationsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        dataHash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        parityHash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          locationsBuilder_.clear();
        }
        recoverId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ytfs.service.packet.MessageRebuild.internal_static_TaskDescription_descriptor;
      }

      public com.ytfs.service.packet.MessageRebuild.TaskDescription getDefaultInstanceForType() {
        return com.ytfs.service.packet.MessageRebuild.TaskDescription.getDefaultInstance();
      }

      public com.ytfs.service.packet.MessageRebuild.TaskDescription build() {
        com.ytfs.service.packet.MessageRebuild.TaskDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ytfs.service.packet.MessageRebuild.TaskDescription buildPartial() {
        com.ytfs.service.packet.MessageRebuild.TaskDescription result = new com.ytfs.service.packet.MessageRebuild.TaskDescription(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          dataHash_ = java.util.Collections.unmodifiableList(dataHash_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.dataHash_ = dataHash_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          parityHash_ = java.util.Collections.unmodifiableList(parityHash_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parityHash_ = parityHash_;
        if (locationsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            locations_ = java.util.Collections.unmodifiableList(locations_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.locations_ = locations_;
        } else {
          result.locations_ = locationsBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          recoverId_ = java.util.Collections.unmodifiableList(recoverId_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.recoverId_ = recoverId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ytfs.service.packet.MessageRebuild.TaskDescription) {
          return mergeFrom((com.ytfs.service.packet.MessageRebuild.TaskDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ytfs.service.packet.MessageRebuild.TaskDescription other) {
        if (other == com.ytfs.service.packet.MessageRebuild.TaskDescription.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.dataHash_.isEmpty()) {
          if (dataHash_.isEmpty()) {
            dataHash_ = other.dataHash_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataHashIsMutable();
            dataHash_.addAll(other.dataHash_);
          }
          onChanged();
        }
        if (!other.parityHash_.isEmpty()) {
          if (parityHash_.isEmpty()) {
            parityHash_ = other.parityHash_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParityHashIsMutable();
            parityHash_.addAll(other.parityHash_);
          }
          onChanged();
        }
        if (locationsBuilder_ == null) {
          if (!other.locations_.isEmpty()) {
            if (locations_.isEmpty()) {
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureLocationsIsMutable();
              locations_.addAll(other.locations_);
            }
            onChanged();
          }
        } else {
          if (!other.locations_.isEmpty()) {
            if (locationsBuilder_.isEmpty()) {
              locationsBuilder_.dispose();
              locationsBuilder_ = null;
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000008);
              locationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLocationsFieldBuilder() : null;
            } else {
              locationsBuilder_.addAllMessages(other.locations_);
            }
          }
        }
        if (!other.recoverId_.isEmpty()) {
          if (recoverId_.isEmpty()) {
            recoverId_ = other.recoverId_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureRecoverIdIsMutable();
            recoverId_.addAll(other.recoverId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ytfs.service.packet.MessageRebuild.TaskDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ytfs.service.packet.MessageRebuild.TaskDescription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> dataHash_ = java.util.Collections.emptyList();
      private void ensureDataHashIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          dataHash_ = new java.util.ArrayList<com.google.protobuf.ByteString>(dataHash_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes dataHash = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDataHashList() {
        return java.util.Collections.unmodifiableList(dataHash_);
      }
      /**
       * <code>repeated bytes dataHash = 2;</code>
       */
      public int getDataHashCount() {
        return dataHash_.size();
      }
      /**
       * <code>repeated bytes dataHash = 2;</code>
       */
      public com.google.protobuf.ByteString getDataHash(int index) {
        return dataHash_.get(index);
      }
      /**
       * <code>repeated bytes dataHash = 2;</code>
       */
      public Builder setDataHash(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataHashIsMutable();
        dataHash_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes dataHash = 2;</code>
       */
      public Builder addDataHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataHashIsMutable();
        dataHash_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes dataHash = 2;</code>
       */
      public Builder addAllDataHash(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDataHashIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataHash_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes dataHash = 2;</code>
       */
      public Builder clearDataHash() {
        dataHash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> parityHash_ = java.util.Collections.emptyList();
      private void ensureParityHashIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          parityHash_ = new java.util.ArrayList<com.google.protobuf.ByteString>(parityHash_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes parityHash = 3;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getParityHashList() {
        return java.util.Collections.unmodifiableList(parityHash_);
      }
      /**
       * <code>repeated bytes parityHash = 3;</code>
       */
      public int getParityHashCount() {
        return parityHash_.size();
      }
      /**
       * <code>repeated bytes parityHash = 3;</code>
       */
      public com.google.protobuf.ByteString getParityHash(int index) {
        return parityHash_.get(index);
      }
      /**
       * <code>repeated bytes parityHash = 3;</code>
       */
      public Builder setParityHash(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParityHashIsMutable();
        parityHash_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes parityHash = 3;</code>
       */
      public Builder addParityHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParityHashIsMutable();
        parityHash_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes parityHash = 3;</code>
       */
      public Builder addAllParityHash(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParityHashIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parityHash_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes parityHash = 3;</code>
       */
      public Builder clearParityHash() {
        parityHash_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<com.ytfs.service.packet.MessageRebuild.P2PLocation> locations_ =
        java.util.Collections.emptyList();
      private void ensureLocationsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          locations_ = new java.util.ArrayList<com.ytfs.service.packet.MessageRebuild.P2PLocation>(locations_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ytfs.service.packet.MessageRebuild.P2PLocation, com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder, com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder> locationsBuilder_;

      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public java.util.List<com.ytfs.service.packet.MessageRebuild.P2PLocation> getLocationsList() {
        if (locationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(locations_);
        } else {
          return locationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public int getLocationsCount() {
        if (locationsBuilder_ == null) {
          return locations_.size();
        } else {
          return locationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public com.ytfs.service.packet.MessageRebuild.P2PLocation getLocations(int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);
        } else {
          return locationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder setLocations(
          int index, com.ytfs.service.packet.MessageRebuild.P2PLocation value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.set(index, value);
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder setLocations(
          int index, com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.set(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder addLocations(com.ytfs.service.packet.MessageRebuild.P2PLocation value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder addLocations(
          int index, com.ytfs.service.packet.MessageRebuild.P2PLocation value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(index, value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder addLocations(
          com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder addLocations(
          int index, com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder addAllLocations(
          java.lang.Iterable<? extends com.ytfs.service.packet.MessageRebuild.P2PLocation> values) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, locations_);
          onChanged();
        } else {
          locationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder clearLocations() {
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          locationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public Builder removeLocations(int index) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.remove(index);
          onChanged();
        } else {
          locationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder getLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder getLocationsOrBuilder(
          int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);  } else {
          return locationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public java.util.List<? extends com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder> 
           getLocationsOrBuilderList() {
        if (locationsBuilder_ != null) {
          return locationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(locations_);
        }
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder addLocationsBuilder() {
        return getLocationsFieldBuilder().addBuilder(
            com.ytfs.service.packet.MessageRebuild.P2PLocation.getDefaultInstance());
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder addLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().addBuilder(
            index, com.ytfs.service.packet.MessageRebuild.P2PLocation.getDefaultInstance());
      }
      /**
       * <code>repeated .P2PLocation locations = 4;</code>
       */
      public java.util.List<com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder> 
           getLocationsBuilderList() {
        return getLocationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ytfs.service.packet.MessageRebuild.P2PLocation, com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder, com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder> 
          getLocationsFieldBuilder() {
        if (locationsBuilder_ == null) {
          locationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ytfs.service.packet.MessageRebuild.P2PLocation, com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder, com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder>(
                  locations_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          locations_ = null;
        }
        return locationsBuilder_;
      }

      private java.util.List<java.lang.Integer> recoverId_ = java.util.Collections.emptyList();
      private void ensureRecoverIdIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          recoverId_ = new java.util.ArrayList<java.lang.Integer>(recoverId_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated uint32 recoverId = 5;</code>
       */
      public java.util.List<java.lang.Integer>
          getRecoverIdList() {
        return java.util.Collections.unmodifiableList(recoverId_);
      }
      /**
       * <code>repeated uint32 recoverId = 5;</code>
       */
      public int getRecoverIdCount() {
        return recoverId_.size();
      }
      /**
       * <code>repeated uint32 recoverId = 5;</code>
       */
      public int getRecoverId(int index) {
        return recoverId_.get(index);
      }
      /**
       * <code>repeated uint32 recoverId = 5;</code>
       */
      public Builder setRecoverId(
          int index, int value) {
        ensureRecoverIdIsMutable();
        recoverId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 recoverId = 5;</code>
       */
      public Builder addRecoverId(int value) {
        ensureRecoverIdIsMutable();
        recoverId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 recoverId = 5;</code>
       */
      public Builder addAllRecoverId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRecoverIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recoverId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 recoverId = 5;</code>
       */
      public Builder clearRecoverId() {
        recoverId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TaskDescription)
    }

    // @@protoc_insertion_point(class_scope:TaskDescription)
    private static final com.ytfs.service.packet.MessageRebuild.TaskDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ytfs.service.packet.MessageRebuild.TaskDescription();
    }

    public static com.ytfs.service.packet.MessageRebuild.TaskDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskDescription>
        PARSER = new com.google.protobuf.AbstractParser<TaskDescription>() {
      public TaskDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskDescription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskDescription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskDescription> getParserForType() {
      return PARSER;
    }

    public com.ytfs.service.packet.MessageRebuild.TaskDescription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface P2PLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:P2PLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nodeId = 1;</code>
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 1;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>repeated string addrs = 2;</code>
     */
    java.util.List<java.lang.String>
        getAddrsList();
    /**
     * <code>repeated string addrs = 2;</code>
     */
    int getAddrsCount();
    /**
     * <code>repeated string addrs = 2;</code>
     */
    java.lang.String getAddrs(int index);
    /**
     * <code>repeated string addrs = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddrsBytes(int index);
  }
  /**
   * Protobuf type {@code P2PLocation}
   */
  public  static final class P2PLocation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:P2PLocation)
      P2PLocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use P2PLocation.newBuilder() to construct.
    private P2PLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private P2PLocation() {
      nodeId_ = "";
      addrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private P2PLocation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                addrs_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              addrs_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          addrs_ = addrs_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ytfs.service.packet.MessageRebuild.internal_static_P2PLocation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ytfs.service.packet.MessageRebuild.internal_static_P2PLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ytfs.service.packet.MessageRebuild.P2PLocation.class, com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder.class);
    }

    private int bitField0_;
    public static final int NODEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object nodeId_;
    /**
     * <code>string nodeId = 1;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList addrs_;
    /**
     * <code>repeated string addrs = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddrsList() {
      return addrs_;
    }
    /**
     * <code>repeated string addrs = 2;</code>
     */
    public int getAddrsCount() {
      return addrs_.size();
    }
    /**
     * <code>repeated string addrs = 2;</code>
     */
    public java.lang.String getAddrs(int index) {
      return addrs_.get(index);
    }
    /**
     * <code>repeated string addrs = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddrsBytes(int index) {
      return addrs_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNodeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
      }
      for (int i = 0; i < addrs_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addrs_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNodeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addrs_.size(); i++) {
          dataSize += computeStringSizeNoTag(addrs_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddrsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ytfs.service.packet.MessageRebuild.P2PLocation)) {
        return super.equals(obj);
      }
      com.ytfs.service.packet.MessageRebuild.P2PLocation other = (com.ytfs.service.packet.MessageRebuild.P2PLocation) obj;

      boolean result = true;
      result = result && getNodeId()
          .equals(other.getNodeId());
      result = result && getAddrsList()
          .equals(other.getAddrsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      if (getAddrsCount() > 0) {
        hash = (37 * hash) + ADDRS_FIELD_NUMBER;
        hash = (53 * hash) + getAddrsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ytfs.service.packet.MessageRebuild.P2PLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ytfs.service.packet.MessageRebuild.P2PLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code P2PLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:P2PLocation)
        com.ytfs.service.packet.MessageRebuild.P2PLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ytfs.service.packet.MessageRebuild.internal_static_P2PLocation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ytfs.service.packet.MessageRebuild.internal_static_P2PLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ytfs.service.packet.MessageRebuild.P2PLocation.class, com.ytfs.service.packet.MessageRebuild.P2PLocation.Builder.class);
      }

      // Construct using com.ytfs.service.packet.MessageRebuild.P2PLocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        nodeId_ = "";

        addrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ytfs.service.packet.MessageRebuild.internal_static_P2PLocation_descriptor;
      }

      public com.ytfs.service.packet.MessageRebuild.P2PLocation getDefaultInstanceForType() {
        return com.ytfs.service.packet.MessageRebuild.P2PLocation.getDefaultInstance();
      }

      public com.ytfs.service.packet.MessageRebuild.P2PLocation build() {
        com.ytfs.service.packet.MessageRebuild.P2PLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ytfs.service.packet.MessageRebuild.P2PLocation buildPartial() {
        com.ytfs.service.packet.MessageRebuild.P2PLocation result = new com.ytfs.service.packet.MessageRebuild.P2PLocation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.nodeId_ = nodeId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          addrs_ = addrs_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.addrs_ = addrs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ytfs.service.packet.MessageRebuild.P2PLocation) {
          return mergeFrom((com.ytfs.service.packet.MessageRebuild.P2PLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ytfs.service.packet.MessageRebuild.P2PLocation other) {
        if (other == com.ytfs.service.packet.MessageRebuild.P2PLocation.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          onChanged();
        }
        if (!other.addrs_.isEmpty()) {
          if (addrs_.isEmpty()) {
            addrs_ = other.addrs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAddrsIsMutable();
            addrs_.addAll(other.addrs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ytfs.service.packet.MessageRebuild.P2PLocation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ytfs.service.packet.MessageRebuild.P2PLocation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 1;</code>
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       */
      public Builder clearNodeId() {
        
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList addrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddrsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          addrs_ = new com.google.protobuf.LazyStringArrayList(addrs_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddrsList() {
        return addrs_.getUnmodifiableView();
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public int getAddrsCount() {
        return addrs_.size();
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public java.lang.String getAddrs(int index) {
        return addrs_.get(index);
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddrsBytes(int index) {
        return addrs_.getByteString(index);
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public Builder setAddrs(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddrsIsMutable();
        addrs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public Builder addAddrs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddrsIsMutable();
        addrs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public Builder addAllAddrs(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddrsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addrs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public Builder clearAddrs() {
        addrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string addrs = 2;</code>
       */
      public Builder addAddrsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddrsIsMutable();
        addrs_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:P2PLocation)
    }

    // @@protoc_insertion_point(class_scope:P2PLocation)
    private static final com.ytfs.service.packet.MessageRebuild.P2PLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ytfs.service.packet.MessageRebuild.P2PLocation();
    }

    public static com.ytfs.service.packet.MessageRebuild.P2PLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<P2PLocation>
        PARSER = new com.google.protobuf.AbstractParser<P2PLocation>() {
      public P2PLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new P2PLocation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<P2PLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<P2PLocation> getParserForType() {
      return PARSER;
    }

    public com.ytfs.service.packet.MessageRebuild.P2PLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskDescription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskDescription_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_P2PLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_P2PLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025message_rebuild.proto\"w\n\017TaskDescripti" +
      "on\022\n\n\002id\030\001 \001(\r\022\020\n\010dataHash\030\002 \003(\014\022\022\n\npari" +
      "tyHash\030\003 \003(\014\022\037\n\tlocations\030\004 \003(\0132\014.P2PLoc" +
      "ation\022\021\n\trecoverId\030\005 \003(\r\",\n\013P2PLocation\022" +
      "\016\n\006nodeId\030\001 \001(\t\022\r\n\005addrs\030\002 \003(\tB\031\n\027com.yt" +
      "fs.service.packetb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TaskDescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TaskDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskDescription_descriptor,
        new java.lang.String[] { "Id", "DataHash", "ParityHash", "Locations", "RecoverId", });
    internal_static_P2PLocation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_P2PLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_P2PLocation_descriptor,
        new java.lang.String[] { "NodeId", "Addrs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
